// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC77wzaJikjN59xSDkrzK5knqBJbl5Ij7Y',
    appId: '1:758042373726:web:3a53fdf689cea04f850ecf',
    messagingSenderId: '758042373726',
    projectId: 'digital-tutor-cep',
    authDomain: 'digital-tutor-cep.firebaseapp.com',
    storageBucket: 'digital-tutor-cep.firebasestorage.app',
    measurementId: 'G-EX4P4JJPYN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD9k2GclrChOh8EuRlZTsZtXyWl85FesAI',
    appId: '1:758042373726:android:086cf4c5b7a3f96e850ecf',
    messagingSenderId: '758042373726',
    projectId: 'digital-tutor-cep',
    storageBucket: 'digital-tutor-cep.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRL6SHuBsXSqikg-OB3zBwHeyS53hpVmc',
    appId: '1:758042373726:ios:b0da849b57c0e75e850ecf',
    messagingSenderId: '758042373726',
    projectId: 'digital-tutor-cep',
    storageBucket: 'digital-tutor-cep.firebasestorage.app',
    iosBundleId: 'com.example.digitalTutor',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRL6SHuBsXSqikg-OB3zBwHeyS53hpVmc',
    appId: '1:758042373726:ios:b0da849b57c0e75e850ecf',
    messagingSenderId: '758042373726',
    projectId: 'digital-tutor-cep',
    storageBucket: 'digital-tutor-cep.firebasestorage.app',
    iosBundleId: 'com.example.digitalTutor',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC77wzaJikjN59xSDkrzK5knqBJbl5Ij7Y',
    appId: '1:758042373726:web:00dd777ddfe5ae90850ecf',
    messagingSenderId: '758042373726',
    projectId: 'digital-tutor-cep',
    authDomain: 'digital-tutor-cep.firebaseapp.com',
    storageBucket: 'digital-tutor-cep.firebasestorage.app',
    measurementId: 'G-9PJV6XF4QF',
  );
}
